// app/data.ts
import { User, LiveCommunity } from './types';

export const i18nData: Record<string, any> = {
  "日本語": { feed: "フィード", discover: "見つける", match: "マッチ", diary: "ダイアリー", chat: "チャット", profile: "プロフィール", searchPlaceholder: "楽曲やアーティストを検索...", settings: "設定", cancel: "キャンセル", postVibe: "記録する", audio: "オーディオプレビュー", notifications: "通知", privateAcc: "プライベートアカウント", timezone: "タイムゾーン", language: "言語設定", logout: "ログアウト", features: "機能", appInfo: "このアプリについて", shareApp: "Echoesをシェア", rateApp: "Echoesを評価する", help: "ヘルプ", editProfile: "プロフィールを編集", artist: "アーティスト", topResults: "トップの結果", allSongs: "すべての楽曲", latestRelease: "最新の楽曲", popularSongs: "人気の楽曲", popularAlbums: "人気のアルバム", followers: "フォロワー", rewind: "Echoes Rewind", overwriteVibe: "上書きして記録", alreadyPostedWarning: "今日はすでに記録済みです。新しく記録すると上書きされます。", favoriteArtists: "お気に入りアーティスト", postSuccess: "記録が完了しました！", sendMessage: "メッセージを送る", typeMessage: "メッセージを入力...", vibeMatchAnalysis: "Vibe 分析", topSharedArtists: "共通のトップアーティスト", sharedGenres: "共通のジャンル", noPreview: "プレビュー音源がありません", pass: "スキップ", connect: "気になる", friendsChat: "フレンド", matchesChat: "マッチ", groupsChat: "グループ", communityChat: "コミュニティ", liveHistory: "ライブ参戦履歴", hashtags: "ハッシュタグ" },
  "English": { feed: "Feed", discover: "Discover", match: "Match", diary: "Diary", chat: "Chat", profile: "Profile", searchPlaceholder: "Search music or artists...", settings: "Settings", cancel: "Cancel", postVibe: "Record", audio: "Audio Preview", notifications: "Notifications", privateAcc: "Private Account", timezone: "Time Zone", language: "Language", logout: "Log Out", features: "Features", appInfo: "About App", shareApp: "Share", rateApp: "Rate", help: "Help", editProfile: "Edit Profile", artist: "Artist", topResults: "Top Results", allSongs: "All Songs", latestRelease: "Latest Release", popularSongs: "Popular Songs", popularAlbums: "Popular Albums", followers: "Followers", rewind: "Echoes Rewind", overwriteVibe: "Overwrite", alreadyPostedWarning: "Already posted today.", favoriteArtists: "Favorite Artists", postSuccess: "Vibe recorded!", sendMessage: "Message", typeMessage: "Type...", vibeMatchAnalysis: "Vibe Analysis", topSharedArtists: "Top Shared Artists", sharedGenres: "Shared Genres", noPreview: "No preview available.", pass: "Skip", connect: "Interested", friendsChat: "Friends", matchesChat: "Matches", groupsChat: "Groups", communityChat: "Community", liveHistory: "Live History", hashtags: "Hashtags" }
};

export const initialMockUsers: User[] = [
  { id: "u1", handle: "anzuuumo", name: "杏夏", avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&q=80", bio: "Alternative & Indie", followers: 4200, following: 50, isPrivate: false, category: 'suggested', topArtists: ["Tele", "Vaundy", "King Gnu"], hashtags: ["邦ロック好きな人と繋がりたい", "Tele"], liveHistory: ["VIVA LA ROCK 2026", "Tele ツアー2026"], age: 22, gender: "female" },
  { id: "u2", handle: "ayk_21", name: "あやか", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80", bio: "チルい曲好き。", followers: 89, following: 120, isPrivate: true, category: 'suggested', topArtists: ["藤井風", "ヨルシカ"], hashtags: ["チルい曲"], liveHistory: ["藤井風 日産スタジアム"], age: 21, gender: "female" },
  { id: "u3", handle: "kuma479", name: "くま", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80", bio: "Western music lover", followers: 200, following: 180, isPrivate: false, category: 'suggested', topArtists: ["Taylor Swift"], hashtags: ["洋楽"], liveHistory: ["Taylor Swift Tokyo Dome"], age: 24, gender: "male" },
  { id: "u4", handle: "vgueda", name: "Daiki", avatar: "https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=400&q=80", bio: "Band", followers: 200, following: 180, isPrivate: false, category: 'suggested', topArtists: ["ONE OK ROCK", "Saucy Dog"], hashtags: ["フェス勢", "サウシードッグ"], liveHistory: ["ROCK IN JAPAN 2026"], age: 23, gender: "male" },
  { id: "s1", handle: "rock_boy99", name: "Ken", avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&q=80", bio: "マカロニえんぴつ好き", followers: 150, following: 200, isPrivate: false, category: 'similar', topArtists: ["マカロニえんぴつ"], hashtags: ["マカえん", "邦ロック"], liveHistory: ["マカロニえんぴつ アリーナツアー"], age: 20, gender: "male" }
];

export const initialMockCommunities: LiveCommunity[] = [
  { id: "com1", name: "VIVA LA ROCK 2026 参戦組", date: "2026-05-03", memberCount: 142, isJoined: false },
  { id: "com2", name: "THE MUSIC STADIUM 2026", date: "2026-04-04", memberCount: 520, isJoined: false },
  { id: "com3", name: "CENTRAL MUSIC FESTIVAL", date: "2026-04-20", memberCount: 305, isJoined: false },
  { id: "com4", name: "Tele ツアー2026", date: "2026-06-10", memberCount: 89, isJoined: false },
];